### ISSUE TITLE
Compatibility with Solidus 2.1.0?

### ISSUE THREAD

**Issue by funwhilelost** [solidusio-contrib/solidus_tax_cloud#1]
The gem currently specifies solidus_core ~> 2.0.0 - has it been tested with 2.1.0?

**Comment by brchristian** [comment]
@funwhilelost 2.1.0 _substantially_ changed the way taxes are computed and the current `master` isn’t 2.1.0-compatible yet. PRs welcome!

**Comment by funwhilelost** [comment]
Ah, gotcha.  I'll see what I can come up with.  Mostly focused on getting my store live at the moment but I'll see how far I get.

**Comment by brchristian** [comment]
Same. We are launching in 2.0, and then from there setting our sights on 2.1. I am happy to create a 2.1 branch with some of my own work to date, with the caveat that it’s totally incomplete at the moment.

**Comment by funwhilelost** [comment]
That would be a great start. I forked just to update the Gemspec and see
what happens. Mixed results.

**Comment by brchristian** [comment]
:+1: My work in progress is now pushed to a `v2.1` branch. Note that this is _NOT_ production ready, as there are still some significant things to be reworked.

**Comment by brchristian** [comment]
You may already know about this, but the release notes will give a good rundown of what the big changes are: https://github.com/solidusio/solidus/releases

**Comment by rlasch** [comment]
I created a PR that I _think_ does this.  Just waiting on someone to take a look at this.  The other piece of work I did was to change the name of the gem from spree tax cloud to solidus tax cloud.  I kept the namespacing, but changed the name of the gem, etc.  Any reason not to push a PR up for that too?

**Comment by brchristian** [comment]
@rlasch It looks to me like your PR is more about discounts than it is about Solidus 2.1? Either way, we have been wanting discount functionality for ages, so thank you for this! I will try to review later this week.

@funwhilelost Happy to report that the `master` and `v2.1` branches of this gem are now Solidus 2.1 compatible. :) We are going to be moving it into production this week, but tests are looking good right now. The only things that have changed since Solidus 2.0:

1) Now item tax and shipping tax are computed in the same checkout step, instead of in two successive steps. I had to change a few test specs accordingly.

2) It seems that Solidus 2.1 displays "Tax: $0.00" whereas Solidus 2.0 simply did not display anything. This is a low-priority issue IMO and shouldn’t affect overall compatibility and isn’t a showstopper for us in terms of moving this into production, but is something to be aware of. Currently I’m not sure if it is better to (a) ensure we don’t create zero-valued Adjustments, _or_, (b) create them but suppress them in the front-end. Waiting for clarity from the Solidus team on the best practice there.

As a result of having a 2.1-viable branch now, I am closing this issue! If you notice any glitches, feel free to open other issues or PRs as things come up. Next stop, Solidus 2.2. :)
