### ISSUE TITLE
USPS ID is no longer required by TaxCloud API

### ISSUE THREAD

**Issue by funwhilelost** [solidusio-contrib/solidus_tax_cloud#3]
There's a note in their [API docs](https://api.taxcloud.com/1.0/) that you can just use the ID `000CLOUD0000`.  Maybe the field could be removed from the settings page.

**Comment by brchristian** [comment]
Oh, cool. That may be new since the last time I checked the docs. I believe that the querying to TaxCloud goes through a dependency to [drewtempelmeyer/tax_cloud](https://github.com/drewtempelmeyer/tax_cloud). We may need to confirm that his `tax_cloud` gem uses the latest version of the TaxCloud API. Feel free to dig around and see if it works. Overall, I’m open to this simplification.

**Comment by funwhilelost** [comment]
Yeah, definitely worth checking out.  IIRC Solidus branched off of Spree at 2.4 so you might be able to get the upstream changes from https://github.com/spree-contrib/spree_tax_cloud/commit/f22f0e7347224ae397c5e686f65bf31d6cfd4c23

I'll take a peek, too, cause I'd love to hook into this API from my new Solidus store.

**Comment by brchristian** [comment]
@funwhilelost Thanks for reporting this, apologies for the long delay, and you’re 100% correct. The current `master` now no longer uses this configuration preference. Cheers! 👍
